language: ruby
cache: bundler
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
- ruby-head
matrix:
  include:
    - rvm: jruby-9.2.18.0
      name: "Latest JRuby"
  allow_failures:
    - rvm: ruby-head
    - name: "Latest JRuby"
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: jL1lH/wfeRa5MoZRHvkXcZP/Ch7huFxqzbvhEV7UZhiDUBnApcJWkb346jeLEDYnFObUhqhaCZ1/l4fDeSFg2GgatSfEnoWATFVkIf1e4TTGAePlS+4qqsGOcr+XrjP6CEf4o4JACdLuSoT9dtUFj0xkFLnDWILxneXIrqDE9VU=
  gem: redis-session-store
  on:
    tags: true
    repo: roidrage/redis-session-store
    rvm: 2.6.6
